apiversion: v1
kind: verify-report
metadata:
    tool:
        verifier-version: 1.10.0
        profile:
            VendorType: community
            version: v1.2
        reportDigest: uint64:13995102124110618124
        chart-uri: gosnappass-0.0.1.tgz
        digests:
            chart: sha256:f843a2106310cbd46f7aa6027b075781fda6aa827d85e483d4fe2cf3bdeab52a
            package: ee3ee7a055d37866a25157987dba2cd5c399f6e8e72541125d949d3c9c06bb03
        lastCertifiedTimestamp: "2023-03-02T13:27:50.199516-06:00"
        testedOpenShiftVersion: "4.12"
        supportedOpenShiftVersions: '>=4.3'
        webCatalogOnly: false
    chart:
        name: gosnappass
        home: https://github.com/concerthall/gosnappass
        sources:
            - https://github.com/concerthall/gosnappass
            - https://github.com/concerthall/gosnappass-helm
        version: 0.0.1
        description: Share Passwords Securely
        keywords:
            - secrets
            - passwords
            - snappass
        maintainers: []
        icon: https://raw.githubusercontent.com/concerthall/gosnappass/main/assets/gosnappass.svg
        apiversion: v2
        condition: ""
        tags: ""
        appversion: 0.0.1
        deprecated: false
        annotations:
            charts.openshift.io/name: gosnappass
        kubeversion: '>= 1.15.0'
        dependencies: []
        type: application
    chart-overrides: ""
results:
    - check: v1.0/not-contains-crds
      type: Optional
      outcome: PASS
      reason: Chart does not contain CRDs
    - check: v1.0/has-readme
      type: Optional
      outcome: PASS
      reason: Chart has a README
    - check: v1.0/is-helm-v3
      type: Optional
      outcome: PASS
      reason: API version is V2, used in Helm 3
    - check: v1.1/has-kubeversion
      type: Optional
      outcome: PASS
      reason: Kubernetes version specified
    - check: v1.0/helm-lint
      type: Mandatory
      outcome: PASS
      reason: Helm lint successful
    - check: v1.1/images-are-certified
      type: Optional
      outcome: FAIL
      reason: |-
        Image is not Red Hat certified : ghcr.io/concerthall/gosnappass:latest
        Image is not Red Hat certified : docker.io/redis/redis-stack:latest
        Image is Red Hat certified : registry.access.redhat.com/ubi9/ubi
    - check: v1.0/chart-testing
      type: Optional
      outcome: PASS
      reason: Chart tests have passed
    - check: v1.0/contains-values
      type: Optional
      outcome: PASS
      reason: Values file exist
    - check: v1.0/not-contain-csi-objects
      type: Optional
      outcome: PASS
      reason: CSI objects do not exist
    - check: v1.0/required-annotations-present
      type: Optional
      outcome: PASS
      reason: All required annotations present
    - check: v1.0/signature-is-valid
      type: Optional
      outcome: SKIPPED
      reason: 'Chart is not signed : Signature verification not required'
    - check: v1.0/contains-test
      type: Optional
      outcome: PASS
      reason: Chart test files exist
    - check: v1.0/contains-values-schema
      type: Optional
      outcome: PASS
      reason: Values schema file exist

